<?php

declare(strict_types=1);

namespace Main;

class StorageFileTable
{
    protected $db;

    public function __construct(\PDO $db)
    {
        $this->db =& $db;
    }

    public function createFileTable($storage_id)
    {
        if ($storage_id) {
            $r = $this->db->prepare('select * from storage where id = ?');
            $r->execute([$storage_id]);

            $storage = $r->fetch(\PDO::FETCH_ASSOC);

            if ($storage) {
                $r = $this->db->prepare(
                    'select storage_attribute.*, t.name as type_name
from storage_attribute
left join storage_attribute_type t on t.id = storage_attribute.type_id
where storage_id = ?
order by id'
                );
                $r->execute([$storage_id]);
                $storage['attributes'] = $r->fetchAll(\PDO::FETCH_ASSOC);
            }

            if ($storage) {
                $table = 'file_' . $storage['id'];

                $r = $this->db->prepare('select to_regclass(?)');
                $r->execute([$table]);

                $table_exists = $r->fetchColumn();

                if (! $table_exists) {
                    // Create table

                    $create_index_sql = [
                        "drop index if exists ${table}_lft_rgt_key",
                        "drop index if exists ${table}_modified_key",
                        "drop index if exists ${table}_name_key",
                        "drop index if exists ${table}_parent_id_key",
                        "drop index if exists ${table}_rgt_lft_key",
                        "drop index if exists ${table}_size_key",
                        "drop index if exists ${table}_parent_id_null_name_key",

                        "create index concurrently ${table}_lft_rgt_key on $table (lft, rgt)",
                        "create index concurrently ${table}_modified_key on $table (modified)",
                        "create index concurrently ${table}_name_key on $table (name)",
                        "create index concurrently ${table}_parent_id_key on $table (parent_id)",
                        "create index concurrently ${table}_rgt_lft_key on $table (rgt, lft)",
                        "create index concurrently ${table}_size_key on $table (size)",
                    ];

                    $create_attributes_sql = '';

                    if (! empty($storage['attributes'])) {
                        foreach ($storage['attributes'] as $v) {
                            switch ($v['type_name'] ?? '') {
                                case 'date':
                                    $create_attributes_sql .= sprintf('a%d date,', $v['id']);
                                    break;

                                case 'datetime':
                                    $create_attributes_sql .= sprintf('a%d timestamp with time zone,', $v['id']);
                                    break;

                                case 'float':
                                    $create_attributes_sql .= sprintf('a%d numeric,', $v['id']);
                                    break;

                                case 'integer':
                                    $create_attributes_sql .= sprintf('a%d bigint,', $v['id']);
                                    break;

                                default:
                                    $create_attributes_sql .= sprintf('a%d text,', $v['id']);
                                    break;
                            }

                            $create_index_sql[] = "drop index if exists ${table}_a${v['id']}_key";

                            switch ($v['type_name'] ?? '') {
                                case 'date':
                                case 'datetime':
                                case 'float':
                                case 'integer':
                                    $create_index_sql[] = "create index concurrently ${table}_a${v['id']}_key on $table (a${v['id']})";
                                    break;

                                default:
                                    $create_index_sql[] = "create index concurrently ${table}_a${v['id']}_key on $table (left(a${v['id']}, 100))";
                                    break;
                            }
                        }
                    }

                    $this->db->beginTransaction();

                    $r = $this->db->prepare(
                        "create table $table (
    id bigint generated by default as identity primary key,
    crc bigint,
    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    file text,
    folder boolean,
    image text,
    image_height smallint,
    image_size integer,
    image_width smallint,
    lft bigint,
    mime_type text,
    modified timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name text NOT NULL,
    parent_id bigint,
    rgt bigint,
    size bigint,
    text text,
    type smallint,
$create_attributes_sql
    constraint ${table}_parent_id_fk foreign key (parent_id) references {$table}(id) on delete cascade on update cascade
)"
                    );

                    $r->execute();

                    $this->db->commit();

                    foreach ($create_index_sql as $v) {
                        $r = $this->db->prepare($v);
                        $r->execute();
                    }
                } else {
                    // Alter table

                    // Поля и их типы у текущей таблицы

                    $r = $this->db->prepare(
                        'select a.attname as column, pg_catalog.format_type(a.atttypid, a.atttypmod) as datatype
from pg_catalog.pg_attribute a
where
    a.attnum > 0
    and not a.attisdropped
    and a.attrelid in (
        select c.oid
        from pg_catalog.pg_class c
        left join pg_catalog.pg_namespace n on n.oid = c.relnamespace
        where c.relname = ? and pg_catalog.pg_table_is_visible(c.oid)
    )'
                    );
                    $r->execute([$table]);

                    $current_fields = [];
                    while ($row = $r->fetch(\PDO::FETCH_ASSOC)) {
                        if (preg_match('/^a\d+$/', $row['column'])) {
                            $current_fields[$row['column']] = $row['datatype'];
                        }
                    }

                    $new_fields = ! empty($storage['attributes']) ? array_reduce(
                        $storage['attributes'],
                        function ($r, $v) {
                            $k = 'a' . $v['id'];

                            switch ($v['type_name'] ?? '') {
                                case 'date':
                                    $r[$k] = 'date';
                                    break;

                                case 'datetime':
                                    $r[$k] = 'timestamp with time zone';
                                    break;

                                case 'float':
                                    $r[$k] = 'numeric';
                                    break;

                                case 'integer':
                                    $r[$k] = 'bigint';
                                    break;

                                default:
                                    $r[$k] = 'text';
                                    break;
                            }

                            return $r;
                        },
                        []
                    ) : [];

                    $columns_to_add = array_diff_assoc($new_fields, $current_fields);
                    $columns_to_delete = array_diff_key($current_fields, $new_fields); // тип поля не учитывается
                    $create_index_sql = [];

                    $this->db->beginTransaction();

                    foreach ($columns_to_add as $column => $datatype) {
                        if (isset($current_fields[$column])) {
                            // Alter column type

                            if (in_array($datatype, ['string', 'text']) && ! in_array($current_fields[$column] ?? null, ['string', 'text'])) {
                                $r = $this->db->prepare("drop index if exists ${table}_${column}_key");
                                $r->execute();

                                $create_index_sql[] = "create index concurrently ${table}_${column}_key on $table (left($column, 100))";
                            } elseif (! in_array($datatype, ['string', 'text']) && in_array($current_fields[$column] ?? null, ['string', 'text'])) {
                                $r = $this->db->prepare("drop index if exists ${table}_${column}_key");
                                $r->execute();

                                $create_index_sql[] = "create index concurrently ${table}_${column}_key on $table ($column)";
                            }

                            if (in_array($datatype, ['string', 'text'])) {
                                $r = $this->db->prepare("alter table $table alter column $column type $datatype using $column::$datatype");
                            } else {
                                $r = $this->db->prepare("alter table $table alter column $column type $datatype using null");
                            }

                            $r->execute();
                        } else {
                            // Add column

                            $r = $this->db->prepare("drop index if exists ${table}_${column}_key");
                            $r->execute();

                            $r = $this->db->prepare("alter table $table add column $column $datatype");
                            $r->execute();

                            if (in_array($datatype, ['string', 'text'])) {
                                $create_index_sql[] = "create index concurrently ${table}_${column}_key on $table (left($column, 100))";
                            } else {
                                $create_index_sql[] = "create index concurrently ${table}_${column}_key on $table ($column)";
                            }
                        }
                    }

                    // Delete columns

                    foreach ($columns_to_delete as $column => $datatype) {
                        $r = $this->db->prepare("alter table $table drop if exists $column");
                        $r->execute();
                    }

                    $this->db->commit();

                    // Create indexes

                    foreach ($create_index_sql as $v) {
                        $r = $this->db->prepare($v);
                        $r->execute();
                    }
                }
            }
        }
    }
}
