CREATE TABLE public.storage_attribute_type_lang (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id integer NOT NULL,
    storage_attribute_type_id integer NOT NULL,
    title text NOT NULL,
    CONSTRAINT storage_attribute_type_lang_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT storage_attribute_type_lang_storage_attribute_type_id_fk FOREIGN KEY (storage_attribute_type_id) REFERENCES public.storage_attribute_type(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE public.storage_permission_lang (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id integer NOT NULL,
    storage_permission_id integer NOT NULL,
    title text NOT NULL,
    CONSTRAINT storage_permission_lang_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT storage_permission_lang_storage_permission_id_fk FOREIGN KEY (storage_permission_id) REFERENCES public.storage_permission(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE public.user_role_lang (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id integer NOT NULL,
    user_role_id integer NOT NULL,
    title text NOT NULL,
    CONSTRAINT user_role_lang_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT user_role_lang_user_role_id_fk FOREIGN KEY (user_role_id) REFERENCES public.user_role(id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO public.storage_attribute_type_lang (language_id,storage_attribute_type_id,title) VALUES (1,1,'String'),(1,2,'Text'),(1,3,'Integer'),(1,4,'Float'),(1,5,'Date'),(1,6,'Datetime'),(2,1,'Строка'),(2,2,'Текст'),(2,3,'Целое число'),(2,4,'Число с плавающей точкой'),(2,5,'Дата'),(2,6,'Дата и время');
INSERT INTO public.storage_permission_lang (language_id,storage_permission_id,title) VALUES (1,1,'Full access'),(1,2,'Write'),(1,3,'Read'),(2,1,'Полный доступ'),(2,2,'Редактирование'),(2,3,'Просмотр');
INSERT INTO public.user_role_lang (language_id,user_role_id,title) VALUES (1,1,'Access to the Admin panel'),(1,2,'User management (super administrator)'),(1,3,'Creating and editing File Storages'),(2,1,'Доступ в панель управления'),(2,2,'Создание и редактирование пользователей (супер администратор)'),(2,3,'Создание и редактирование хранилищ');

alter table public.storage_attribute_type drop column title;
alter table public.storage_permission drop column title;
alter table public.user_role drop column title;
