DROP TABLE IF EXISTS public.mail_template CASCADE;
CREATE TABLE public.mail_template (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_id integer NOT NULL,
    name text NOT NULL,
    subject text,
    text text,
    UNIQUE (name,language_id),
    CONSTRAINT setting_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE CASCADE ON UPDATE CASCADE
);

COPY public.mail_template (language_id,name,subject,text) FROM stdin;
1	user_activation	Please activate your Archivarius account	<!doctype html><html xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><style type="text/css">body{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;line-height:1.4;}#outlooka{padding:0;}.ExternalClass{width:100%;}.ExternalClass,.ExternalClassdiv,.ExternalClassfont,.ExternalClassp,.ExternalClassspan,.ExternalClasstd{line-height:1.4;}.ReadMsgBody{width:100%;}</style></head><body><h1>You have been invited to the Archivarius Digital Archive website. Please activate your account</h1><p>To access the files on the Archivarius Digital Archive website, please follow this link. Thank you.</p><h2><a href="{{activation_url}}">Activate your account</a> </h2><p>If you think you received this email by mistake, just ignore it then.</p><p>Sincerely yours, Archivarius team</p><p>st. Pryanishnikova, 19A, stroenie 4. Moscow.<br>Working hours: Monday - Friday, from 9 to 18 hours.<br>+7-495-921-45-72.<br>info@archivarius.ru</p></body></html>
2	user_activation	Активируйте вашу учетную запись на сайте Архивариус электронный архив	<!doctype html><html xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><style type="text/css">body{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;line-height:1.4;}#outlooka{padding:0;}.ExternalClass{width:100%;}.ExternalClass,.ExternalClassdiv,.ExternalClassfont,.ExternalClassp,.ExternalClassspan,.ExternalClasstd{line-height:1.4;}.ReadMsgBody{width:100%;}</style></head><body><h1>Вас пригласили для доступа к файлам на сайте «Архивариус электронный архив», пожалуйста, активируйте вашу учетную запись</h1><p>Чтобы получить доступ к файлам на сайте «Архивариус электронный архив», пожалуйста, нажмите на ссылку. Спасибо.</p><h2><a href="{{activation_url}}">Активировать вашу учетную запись</a></h2><p>Если вы считаете, что получили это письмо по ошибке, — игнорируйте его.</p><p>С уважением,<br>Коллектив компании Архивариус</p><p>Москва, ул. Прянишникова, д. 19А, строение 4.<br>Режим работы: понедельник — пятница, с 9 до 18 часов.<br>+7 495 921-45-72.<br>info@archivarius.ru</p></body></html>
\.
