CREATE TABLE public.language (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean,
    name text NOT NULL,
    title text NOT NULL,
    UNIQUE (name)
);

INSERT INTO public.language (active,name,title) VALUES (true,'en','English'),(true,'ru','Русский');

alter table public."user" add column lang_id integer;

alter table public."user" add constraint user_lang_id_fk FOREIGN KEY (lang_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE;
