SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP TYPE IF EXISTS public.request_type CASCADE;
CREATE TYPE public.request_type AS ENUM (
	'activation',
	'reset'
);

SET default_tablespace = '';
SET default_with_oids = false;

DROP TABLE IF EXISTS public.auth_attempt CASCADE;
CREATE TABLE public.auth_attempt (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	expiredate timestamp with time zone NOT NULL,
	ip character(39) NOT NULL
);

DROP TABLE IF EXISTS public.auth_ban CASCADE;
CREATE TABLE public.auth_ban (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	domain character varying(100)
);

DROP TABLE IF EXISTS public.auth_request CASCADE;
CREATE TABLE public.auth_request (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	expire timestamp with time zone NOT NULL,
	token character(20) NOT NULL,
	type public.request_type NOT NULL,
	uid integer NOT NULL
);

DROP TABLE IF EXISTS public.auth_session CASCADE;
CREATE TABLE public.auth_session (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	agent character varying(200) NOT NULL,
	cookie_crc character(40) NOT NULL,
	device_id text,
	expiredate timestamp with time zone NOT NULL,
	hash character(40) NOT NULL,
	ip character varying(39) NOT NULL,
	uid integer NOT NULL
);

drop table if exists public.cache cascade;
create table public.cache (
	bucket smallint not null,
	expire timestamp with time zone not null,
	key text not null,
	value text,
	primary key (key, bucket)
) partition by range (bucket);

create table public.cache_p0 partition of public.cache for values from (0) to (1);
create table public.cache_p1 partition of public.cache for values from (1) to (2);
create table public.cache_p2 partition of public.cache for values from (2) to (32767);

drop index if exists cache__bucket__key;
create index if not exists cache__bucket__key on public.cache (bucket);

drop index if exists cache__expire__key;
create index if not exists cache__expire__key on public.cache (expire);

drop table if exists public.gue_jobs cascade;
create table if not exists public.gue_jobs (
	job_id bigint generated by default as identity primary key,
	args json not null,
	created_at timestamptz not null,
	error_count integer not null default 0,
	job_type text not null,
	last_error text,
	priority smallint not null,
	queue text not null,
	run_at timestamptz not null,
	updated_at timestamptz not null
);

drop index if exists gue_jobs__selector__key;
create index if not exists gue_jobs__selector__key on public.gue_jobs (queue, run_at, priority);

DROP TABLE IF EXISTS public.language CASCADE;
CREATE TABLE public.language (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	active boolean,
	name text NOT NULL,
	title text NOT NULL,
	UNIQUE (name)
);

DROP TABLE IF EXISTS public.mail_template CASCADE;
CREATE TABLE public.mail_template (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	language_id integer NOT NULL,
	name text NOT NULL,
	subject text,
	text text,
	UNIQUE (name,language_id),
	CONSTRAINT setting_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS public.setting_group CASCADE;
CREATE TABLE public.setting_group (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	name text NOT NULL,
	UNIQUE (name)
);

DROP TABLE IF EXISTS public.setting CASCADE;
CREATE TABLE public.setting (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	group_id integer,
	int_value bigint,
	language_id integer NOT NULL,
	name text NOT NULL,
	number_value numeric,
	text_value text,
	type text,
	UNIQUE (name,language_id),
	CONSTRAINT setting_group_id_fk FOREIGN KEY (group_id) REFERENCES public.setting_group(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT setting_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS public.storage CASCADE;
CREATE TABLE public.storage (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	description text,
	modified timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	search tsvector GENERATED ALWAYS AS (to_tsvector('russian', coalesce(description, '') || ' ' || coalesce(title, '') || ' ' || coalesce(uid, ''))) STORED,
	size bigint,
	title text,
	uid character varying(100) NOT NULL,
	UNIQUE (uid)
);

DROP INDEX if exists storage_search_key;
CREATE INDEX CONCURRENTLY storage_search_key ON public.storage USING gin (search);

DROP INDEX IF EXISTS storage_size_key;
CREATE INDEX storage_size_key ON public.storage (size);

DROP TABLE IF EXISTS public.storage_attribute_type CASCADE;
CREATE TABLE public.storage_attribute_type (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name text,
	sort integer
);

DROP TABLE IF EXISTS public.storage_attribute_type_lang CASCADE;
CREATE TABLE public.storage_attribute_type_lang (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	language_id integer NOT NULL,
	storage_attribute_type_id integer NOT NULL,
	title text NOT NULL,
	CONSTRAINT storage_attribute_type_lang_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT storage_attribute_type_lang_storage_attribute_type_id_fk FOREIGN KEY (storage_attribute_type_id) REFERENCES public.storage_attribute_type(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS public.storage_attribute CASCADE;
CREATE TABLE public.storage_attribute (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	filter boolean,
	sort integer,
	storage_id integer NOT NULL,
	title text NOT NULL,
	type_id integer,
	UNIQUE (storage_id, title),
	CONSTRAINT storage_attribute_storage_id_fk FOREIGN KEY (storage_id) REFERENCES public.storage(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT storage_attribute_type_id_fk FOREIGN KEY (type_id) REFERENCES public.storage_attribute_type(id) ON DELETE SET NULL ON UPDATE CASCADE
);

DROP TABLE IF EXISTS public.log CASCADE;
CREATE TABLE public.log (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	message text,
	storage_id integer,
	search tsvector GENERATED ALWAYS AS (to_tsvector('russian', coalesce(message, ''))) STORED,
	CONSTRAINT log_storage_id_fk FOREIGN KEY (storage_id) REFERENCES public.storage(id) ON DELETE SET NULL ON UPDATE CASCADE
);

DROP INDEX if exists log_created_key;
CREATE INDEX CONCURRENTLY log_created_key ON public.log (created);

DROP INDEX if exists log_search_key;
CREATE INDEX CONCURRENTLY log_search_key ON public.log USING gin (search);

DROP TABLE IF EXISTS public.throttle CASCADE;
CREATE TABLE public.throttle (
	id text NOT NULL PRIMARY KEY,
	count integer NOT NULL,
	expire timestamp with time zone NOT NULL
);

DROP INDEX IF EXISTS throttle_expire_key;
CREATE INDEX throttle_expire_key ON public.throttle (expire);

DROP TABLE IF EXISTS public."user" CASCADE;
CREATE TABLE public."user" (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	description text,
	email character varying(100),
	isactive boolean,
	language_id integer,
	modified timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	name character varying(100),
	password character varying(255),
	search tsvector GENERATED ALWAYS AS (to_tsvector('russian', coalesce(description, '') || ' ' || coalesce(email, '') || ' ' || coalesce(name, ''))) STORED,
	settings text,
	CONSTRAINT user_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE
);

DROP INDEX if exists user_search_key;
CREATE INDEX CONCURRENTLY user_search_key ON public."user" USING gin (search);

DROP TABLE IF EXISTS public.user_role CASCADE;
CREATE TABLE public.user_role (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description text,
	name character varying(100) NOT NULL,
	UNIQUE (name)
);

DROP TABLE IF EXISTS public.user_role_lang CASCADE;
CREATE TABLE public.user_role_lang (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	language_id integer NOT NULL,
	user_role_id integer NOT NULL,
	title text NOT NULL,
	CONSTRAINT user_role_lang_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT user_role_lang_user_role_id_fk FOREIGN KEY (user_role_id) REFERENCES public.user_role(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS public.user_role_user CASCADE;
CREATE TABLE public.user_role_user (
	role_id integer NOT NULL,
	user_id integer NOT NULL,
	PRIMARY KEY (role_id, user_id),
	CONSTRAINT user_role_user_role_id_fk FOREIGN KEY (role_id) REFERENCES public.user_role(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT user_role_user_user_id_fk FOREIGN KEY (user_id) REFERENCES public.user (id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP INDEX IF EXISTS user_role_user_user_id_key;
CREATE INDEX user_role_user_user_id_key ON public.user_role_user (user_id);

DROP TABLE IF EXISTS public.storage_permission CASCADE;
CREATE TABLE public.storage_permission (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name character varying(100) NOT NULL
);

DROP TABLE IF EXISTS public.storage_permission_lang CASCADE;
CREATE TABLE public.storage_permission_lang (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	language_id integer NOT NULL,
	storage_permission_id integer NOT NULL,
	title text NOT NULL,
	CONSTRAINT storage_permission_lang_language_id_fk FOREIGN KEY (language_id) REFERENCES public.language(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT storage_permission_lang_storage_permission_id_fk FOREIGN KEY (storage_permission_id) REFERENCES public.storage_permission(id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS public.storage_user_permission CASCADE;
CREATE TABLE public.storage_user_permission (
	storage_id integer NOT NULL,
	permission_id integer NOT NULL,
	user_id integer NOT NULL,
	PRIMARY KEY (storage_id, user_id),
	CONSTRAINT storage_user_permission_permission_id_fk FOREIGN KEY (permission_id) REFERENCES public.storage_permission (id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT storage_user_permission_storage_id_fk FOREIGN KEY (storage_id) REFERENCES public.storage(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT storage_user_permission_user_id_fk FOREIGN KEY (user_id) REFERENCES public.user (id) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS public.version CASCADE;
CREATE TABLE public.version (
	versionid text NOT NULL
);

DROP INDEX IF EXISTS storage_user_permission_permission_id_key;
CREATE INDEX storage_user_permission_permission_id_key ON public.storage_user_permission (permission_id);

DROP INDEX IF EXISTS storage_user_permission_user_id_key;
CREATE INDEX storage_user_permission_user_id_key ON public.storage_user_permission (user_id);

INSERT INTO public.language (id,active,name,title) VALUES (1,true,'en','English'),(2,true,'ru','Русский');
INSERT INTO public.storage_attribute_type (id,name,sort) VALUES (1,'string',1),(2,'text',null),(3,'integer',null),(4,'float',null),(5,'date',null),(6,'datetime',null);
INSERT INTO public.storage_attribute_type_lang (language_id,storage_attribute_type_id,title) VALUES (1,1,'String'),(1,2,'Text'),(1,3,'Integer'),(1,4,'Float'),(1,5,'Date'),(1,6,'Datetime'),(2,1,'Строка'),(2,2,'Текст'),(2,3,'Целое число'),(2,4,'Число с плавающей точкой'),(2,5,'Дата'),(2,6,'Дата и время');
INSERT INTO public.storage_permission (id,name) VALUES (1,'full'),(2,'edit'),(3,'read_only');
INSERT INTO public.storage_permission_lang (language_id,storage_permission_id,title) VALUES (1,1,'Full access'),(1,2,'Write'),(1,3,'Read'),(2,1,'Полный доступ'),(2,2,'Редактирование'),(2,3,'Просмотр');
INSERT INTO public.user_role (id,name) VALUES (1,'admin'),(2,'user_management'),(3,'storage_management');
INSERT INTO public.user_role_lang (language_id,user_role_id,title) VALUES (1,1,'Access to the Admin panel'),(1,2,'User management (super administrator)'),(1,3,'Creating and editing File Storages'),(2,1,'Доступ в панель управления'),(2,2,'Создание и редактирование пользователей (супер администратор)'),(2,3,'Создание и редактирование хранилищ');
INSERT INTO public.version (versionid) VALUES ('20230803');

COPY public.mail_template (language_id,name,subject,text) FROM stdin;
1	user_activation	Please activate your Archivarius account	<!doctype html><html xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><style type="text/css">body{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;line-height:1.4;}#outlooka{padding:0;}.ExternalClass{width:100%;}.ExternalClass,.ExternalClassdiv,.ExternalClassfont,.ExternalClassp,.ExternalClassspan,.ExternalClasstd{line-height:1.4;}.ReadMsgBody{width:100%;}</style></head><body><h1>You have been invited to the Archivarius Digital Archive website. Please activate your account</h1><p>To access the files on the Archivarius Digital Archive website, please follow this link. Thank you.</p><h2><a href="{{activation_url}}">Activate your account</a> </h2><p>If you think you received this email by mistake, just ignore it then.</p><p>Sincerely yours, Archivarius team</p><p>Avangardnaya Ulitsa, 3, Moscow.<br>Working hours: Monday - Friday, from 9 to 18 hours.<br>+7 495 532-07-32.<br>info@archivarius.ru</p></body></html>
2	user_activation	Активируйте вашу учетную запись на сайте Архивариус электронный архив	<!doctype html><html xmlns="http://www.w3.org/1999/xhtml"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><style type="text/css">body{-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;line-height:1.4;}#outlooka{padding:0;}.ExternalClass{width:100%;}.ExternalClass,.ExternalClassdiv,.ExternalClassfont,.ExternalClassp,.ExternalClassspan,.ExternalClasstd{line-height:1.4;}.ReadMsgBody{width:100%;}</style></head><body><h1>Вас пригласили для доступа к файлам на сайте «Архивариус электронный архив», пожалуйста, активируйте вашу учетную запись</h1><p>Чтобы получить доступ к файлам на сайте «Архивариус электронный архив», пожалуйста, нажмите на ссылку. Спасибо.</p><h2><a href="{{activation_url}}">Активировать вашу учетную запись</a></h2><p>Если вы считаете, что получили это письмо по ошибке, — игнорируйте его.</p><p>С уважением,<br>Коллектив компании Архивариус</p><p>Москва, ул. Авангардная, дом 3. БЦ Сатурн.<br>Режим работы: понедельник — пятница, с 9 до 18 часов.<br>+7 495 532-07-32.<br>info@archivarius.ru</p></body></html>
\.

COPY public.setting_group (id,name) FROM stdin;
1	autoload
2	view
3	admin_autoload
4	admin_view
\.

COPY public.setting (language_id,group_id,name,type,text_value) FROM stdin;
1	1	short_site_name	\N	Archivarius
1	1	site_description	\N	Digital archive
1	1	site_name	\N	Archivarius. Digital archive
1	2	footer_copyright	\N	<div style="margin: 0 0 .5rem;"><a href="https://www.archivarius.ru">archivarius.ru</a></div><div>2004-2020 <a href="https://www.archivarius.ru">ARCHIVARIUS</a></div>
1	2	footer_menu	json	[{"link":"https://www.archivarius.ru/o-kompanii/","title":"About Us"},{"link":"https://www.archivarius.ru/otzyvy/","title":"Customer feedback"},{"link":"https://www.archivarius.ru/dlya-otrasley/","title":"For partners"}]
1	2	footer_text	\N	<div>Avangardnaya Ulitsa, 3, Moscow</div><h3 style="margin:.25rem 0;"><a href="tel:+74955320732"><img src="/static/img/icon_phone_white.svg" style="margin-right:10px;width:15px;">8 495 532-07-32</a></h3><div><a href="mailto:info@archivarius.ru">info@archivarius.ru</a></div>
1	2	header_logo_description	\N	Digital archive
1	2	header_logo_text	\N	Archivarius
1	2	header_logo_url	\N	/static/img/archivarius_logo.png
1	3	admin_site_name	\N	Archivarius Admin Panel
1	4	admin_header_logo_description	\N	Admin Panel
1	4	admin_header_logo_text	\N	Archivarius
2	1	short_site_name	\N	Проект24
2	1	site_description	\N	Электронный архив
2	1	site_name	\N	Проект24. Электронный архив
2	2	footer_copyright	\N	<div style="margin: 0 0 .5rem;"><a href="https://www.archivarius.ru">archivarius.ru</a></div><div>2004-2020 <a href="https://www.archivarius.ru">АРХИВАРИУСЪ</a></div>
2	2	footer_menu	json	[{"link":"https://www.archivarius.ru/o-kompanii/","title":"О компании"},{"link":"https://www.archivarius.ru/otzyvy/","title":"Отзывы клиентов"},{"link":"https://www.archivarius.ru/dlya-otrasley/","title":"Решения для отраслей"}]
2	2	footer_text	\N	<div>Москва, ул.&nbsp;Авангардная, дом&nbsp;3. БЦ&nbsp;Сатурн</div><h3 style="margin:.25rem 0;"><a href="tel:+74955320732"><img src="/static/img/icon_phone_white.svg" style="margin-right:10px;width:15px;">8 495 532-07-32</a></h3><div><a href="mailto:info@archivarius.ru">info@archivarius.ru</a></div>
2	2	header_logo_description	\N	Электронный архив
2	2	header_logo_text	\N	Проект24
2	2	header_logo_url	\N	/static/img/archivarius_logo.png
2	3	admin_site_name	\N	Проект24. Панель управления
2	4	admin_header_logo_description	\N	Панель управления
2	4	admin_header_logo_text	\N	Проект24
\.

-- Пример таблицы хранения файлов
--
-- drop table if exists public.file_1 cascade;
-- create table public.file_1 (
--	id bigint generated by default as identity primary key,
--	crc bigint,
--	created timestamp with time zone default current_timestamp not null,
--	file text,
--	folder boolean,
--	image text,
--	image_height smallint,
--	image_size integer,
--	image_width smallint,
--	lft bigint,
--	mime_type text,
--	modified timestamp with time zone default current_timestamp not null,
--	name text not null,
--	parent_id bigint,
--	rgt bigint,
--	size bigint,
--	text text,
--	type smallint,
--	a2 text,
--	a3 text,
--	a4 text,
--	a6 numeric,
--	a16 int,
--	constraint file_1_parent_id_fk foreign key (parent_id) references public.file_1(id) on delete cascade on update cascade
-- );

-- create index file_1_a16_key on public.file_1 (a16);
-- create index file_1_a2_key on public.file_1 (a2);
-- create index file_1_a3_key on public.file_1 (a3);
-- create index file_1_a4_key on public.file_1 (a4);
-- create index file_1_a6_key on public.file_1 (a6);
-- create index file_1_lft_rgt_key on public.file_1 (lft, rgt);
-- create index file_1_modified_key on public.file_1 (modified);
-- create index file_1_name_key on public.file_1 (name);
-- create index file_1_parent_id_key on public.file_1 (parent_id);
-- create index file_1_rgt_lft_key on public.file_1 (rgt, lft);
-- create index file_1_size_key on public.file_1 (size);
-- create unique index file_1_parent_id_null_name_key on file_1 (name) where parent_id is null;
