-- insert into public."user" (email, isactive) values ('32b100@gmail.com', true);

--COPY public.storage (title, uid) FROM stdin;
--Файлы	SwSeHqpl4G
--\.

--COPY public.storage_user_permission (storage_id, permission_id, user_id) FROM stdin;
--1	1	1
--\.

--CREATE TABLE public.file_1 (
--    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    crc bigint,
--    created timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
--    file text,
--    folder boolean,
--    lft bigint,
--    modified timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
--    name text NOT NULL,
--    parent_id bigint,
--    rgt bigint,
--    size bigint,
--    text text,
--    UNIQUE (parent_id, name),
--    CONSTRAINT file_1_parent_id_fk FOREIGN KEY (parent_id) REFERENCES public.file_1(id) ON DELETE CASCADE ON UPDATE CASCADE
--);

--CREATE INDEX file_1_lft_rgt_key ON public.file_1 (lft, rgt);
--CREATE INDEX file_1_modified_key ON public.file_1 (modified);
--CREATE INDEX file_1_name_key ON public.file_1 (name);
--CREATE INDEX file_1_parent_id_key ON public.file_1 (parent_id);
--CREATE INDEX file_1_rgt_lft_key ON public.file_1 (rgt, lft);
--CREATE INDEX file_1_size_key ON public.file_1 (size);
--CREATE UNIQUE INDEX file_1_parent_id_null_name_key ON file_1 (name) WHERE parent_id IS NULL;
